services:
  api:
    build:
      network: host
      context: ./app
    expose:
      - "8000"
    env_file:
      - .env
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api
